2025-01-26 23:08:48,679 - root - INFO - Bot ishga tushdi
2025-01-26 23:08:48,681 - aiogram.dispatcher - INFO - Start polling
2025-01-26 23:08:49,165 - aiogram.dispatcher - INFO - Run polling for bot @anime_duo_bot id=7861655553 - 'Anime uzb'
2025-01-26 23:08:49,931 - root - INFO - Bot ishga tushdi
2025-01-26 23:08:51,064 - aiogram.event - INFO - Update id=260027116 is handled. Duration 1719 ms by bot id=7861655553
2025-01-26 23:08:57,668 - aiogram.event - INFO - Update id=260027117 is handled. Duration 280 ms by bot id=7861655553
2025-01-26 23:09:00,068 - aiogram.event - INFO - Update id=260027118 is handled. Duration 297 ms by bot id=7861655553
2025-01-26 23:09:02,477 - aiogram.event - INFO - Update id=260027119 is handled. Duration 218 ms by bot id=7861655553
2025-01-26 23:09:05,351 - aiogram.event - INFO - Update id=260027120 is handled. Duration 187 ms by bot id=7861655553
2025-01-26 23:09:08,821 - aiogram.event - INFO - Update id=260027121 is not handled. Duration 0 ms by bot id=7861655553
2025-01-26 23:10:10,640 - aiogram.event - INFO - Update id=260027122 is handled. Duration 718 ms by bot id=7861655553
2025-01-26 23:11:37,642 - aiogram.event - INFO - Update id=260027123 is handled. Duration 2937 ms by bot id=7861655553
2025-01-26 23:12:38,852 - root - INFO - Bot ishga tushdi
2025-01-26 23:12:38,854 - aiogram.dispatcher - INFO - Start polling
2025-01-26 23:12:39,403 - aiogram.dispatcher - INFO - Run polling for bot @anime_duo_bot id=7861655553 - 'Anime uzb'
2025-01-26 23:12:40,421 - aiogram.event - INFO - Update id=260027124 is handled. Duration 781 ms by bot id=7861655553
2025-01-26 23:12:44,353 - aiogram.event - INFO - Update id=260027125 is handled. Duration 187 ms by bot id=7861655553
2025-01-26 23:12:48,561 - aiogram.event - INFO - Update id=260027126 is handled. Duration 234 ms by bot id=7861655553
2025-01-26 23:12:50,763 - aiogram.event - INFO - Update id=260027127 is handled. Duration 265 ms by bot id=7861655553
2025-01-26 23:13:09,875 - aiogram.event - INFO - Update id=260027128 is not handled. Duration 0 ms by bot id=7861655553
2025-01-26 23:14:17,082 - aiogram.dispatcher - INFO - Polling stopped
2025-01-26 23:14:17,333 - aiogram.dispatcher - INFO - Polling stopped for bot @anime_duo_bot id=7861655553 - 'Anime uzb'
2025-01-26 23:14:25,650 - root - INFO - Bot ishga tushdi
2025-01-26 23:14:25,653 - aiogram.dispatcher - INFO - Start polling
2025-01-26 23:14:26,837 - aiogram.dispatcher - INFO - Run polling for bot @anime_duo_bot id=7861655553 - 'Anime uzb'
2025-01-26 23:14:27,881 - aiogram.event - INFO - Update id=260027129 is handled. Duration 641 ms by bot id=7861655553
2025-01-26 23:14:30,093 - aiogram.event - INFO - Update id=260027130 is not handled. Duration 0 ms by bot id=7861655553
2025-01-26 23:15:24,128 - aiogram.dispatcher - INFO - Polling stopped
2025-01-26 23:15:24,380 - aiogram.dispatcher - INFO - Polling stopped for bot @anime_duo_bot id=7861655553 - 'Anime uzb'
2025-01-26 23:15:32,568 - root - INFO - Bot ishga tushdi
2025-01-26 23:15:32,569 - aiogram.dispatcher - INFO - Start polling
2025-01-26 23:15:33,140 - aiogram.dispatcher - INFO - Run polling for bot @anime_duo_bot id=7861655553 - 'Anime uzb'
2025-01-26 23:15:33,953 - aiogram.event - INFO - Update id=260027131 is handled. Duration 577 ms by bot id=7861655553
2025-01-26 23:15:35,765 - aiogram.event - INFO - Update id=260027132 is not handled. Duration 15 ms by bot id=7861655553
2025-01-26 23:15:35,765 - aiogram.event - ERROR - Cause exception while process update id=260027132 by bot id=7861655553
ProgrammingError: Error binding parameter 1: type 'list' is not supported
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 137, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 162, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\user\Documents\GitHub\Duo-telegram-bot\handlers\message.py", line 185, in add_category_msg
    anime.add_category(id,msg_list)
  File "c:\Users\user\Documents\GitHub\Duo-telegram-bot\utils\anime.py", line 105, in add_category
    cursor.execute("UPDATE animes_table SET category = ? WHERE id = ?",(category,anime_id))
sqlite3.ProgrammingError: Error binding parameter 1: type 'list' is not supported
2025-01-26 23:16:54,377 - aiogram.dispatcher - INFO - Polling stopped
2025-01-26 23:16:54,629 - aiogram.dispatcher - INFO - Polling stopped for bot @anime_duo_bot id=7861655553 - 'Anime uzb'
2025-01-26 23:17:06,369 - root - INFO - Bot ishga tushdi
2025-01-26 23:17:06,371 - aiogram.dispatcher - INFO - Start polling
2025-01-26 23:17:06,974 - aiogram.dispatcher - INFO - Run polling for bot @anime_duo_bot id=7861655553 - 'Anime uzb'
2025-01-26 23:17:07,693 - aiogram.event - INFO - Update id=260027133 is handled. Duration 532 ms by bot id=7861655553
2025-01-26 23:17:10,417 - aiogram.event - INFO - Update id=260027134 is handled. Duration 265 ms by bot id=7861655553
2025-01-26 23:17:42,155 - aiogram.event - INFO - Update id=260027135 is handled. Duration 625 ms by bot id=7861655553
2025-01-26 23:18:31,566 - aiogram.event - INFO - Update id=260027136 is handled. Duration 515 ms by bot id=7861655553
2025-01-26 23:18:53,568 - aiogram.event - INFO - Update id=260027137 is handled. Duration 594 ms by bot id=7861655553
2025-01-26 23:19:01,467 - aiogram.event - INFO - Update id=260027138 is not handled. Duration 15 ms by bot id=7861655553
2025-01-26 23:19:01,467 - aiogram.event - ERROR - Cause exception while process update id=260027138 by bot id=7861655553
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 137, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\router.py", line 162, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\user\Documents\GitHub\Duo-telegram-bot\handlers\message.py", line 195, in rem_category_msg
    c,id = message.text.split(",")
    ^^^^
ValueError: not enough values to unpack (expected 2, got 1)
2025-01-26 23:20:14,477 - aiogram.dispatcher - INFO - Polling stopped
2025-01-26 23:20:14,729 - aiogram.dispatcher - INFO - Polling stopped for bot @anime_duo_bot id=7861655553 - 'Anime uzb'
2025-01-26 23:20:25,320 - root - INFO - Bot ishga tushdi
2025-01-26 23:20:25,322 - aiogram.dispatcher - INFO - Start polling
2025-01-26 23:20:26,057 - aiogram.dispatcher - INFO - Run polling for bot @anime_duo_bot id=7861655553 - 'Anime uzb'
2025-01-26 23:20:26,807 - aiogram.event - INFO - Update id=260027139 is handled. Duration 563 ms by bot id=7861655553
2025-01-26 23:20:30,981 - aiogram.event - INFO - Update id=260027140 is handled. Duration 218 ms by bot id=7861655553
